#!/usr/bin/env python3
"""Run MASt3R-SLAM on a GRABETTE episode and emit a grabette-format
camera_trajectory.csv that the visualize_trajectory.py tool from grabette-data
can consume.

Pipeline
--------
1. Read the ORB-SLAM3-style settings YAML for the camera (KannalaBrandt8 fisheye).
2. Undistort raw_video.mp4 to a pinhole projection (cv2.fisheye.* APIs).
3. Generate a pinhole intrinsics.yaml for MASt3R-SLAM.
4. Run MASt3R-SLAM via main.py against the pinhole mp4.
5. Convert the TUM keyframe trajectory in logs/<save_as>/ into the grabette
   per-frame CSV format (sparse — only keyframe rows are tracked,
   non-keyframe rows have is_lost=true).

Run from inside the docker container after `uv sync`:

    uv run python scripts/run_grabette_episode.py \\
        --episode test_data/grabette9 \\
        --calib   test_data/rpi_bmi088_slam_settings.yaml \\
        --save-as grabette9
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

import cv2
import numpy as np
import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# Calibration parsing
# ---------------------------------------------------------------------------


def load_orbslam3_yaml(path: Path) -> dict:
    """Load an OpenCV-style YAML (the leading `%YAML:1.0` and `!!opencv-matrix`
    tags trip up vanilla PyYAML; strip them out).
    """
    text = path.read_text()
    # Drop the `%YAML:1.0` directive.
    text = "\n".join(line for line in text.splitlines() if not line.startswith("%YAML"))
    # Replace OpenCV matrix tags so PyYAML doesn't choke.
    text = text.replace("!!opencv-matrix", "")
    return yaml.safe_load(text)


def extract_fisheye_intrinsics(cfg: dict) -> tuple[np.ndarray, np.ndarray, tuple[int, int]]:
    """Return (K, D, (W,H)) for the fisheye camera defined in the YAML."""
    if cfg.get("Camera.type") != "KannalaBrandt8":
        raise ValueError(
            f"Expected Camera.type=KannalaBrandt8, got {cfg.get('Camera.type')!r}"
        )
    K = np.array(
        [
            [cfg["Camera1.fx"], 0.0, cfg["Camera1.cx"]],
            [0.0, cfg["Camera1.fy"], cfg["Camera1.cy"]],
            [0.0, 0.0, 1.0],
        ],
        dtype=np.float64,
    )
    D = np.array(
        [cfg["Camera1.k1"], cfg["Camera1.k2"], cfg["Camera1.k3"], cfg["Camera1.k4"]],
        dtype=np.float64,
    )
    size = (int(cfg["Camera.width"]), int(cfg["Camera.height"]))
    return K, D, size


# ---------------------------------------------------------------------------
# Undistortion
# ---------------------------------------------------------------------------


def undistort_video(
    src: Path,
    dst: Path,
    K: np.ndarray,
    D: np.ndarray,
    size: tuple[int, int],
    balance: float = 0.0,
) -> tuple[np.ndarray, float, int]:
    """Convert a KannalaBrandt8 fisheye mp4 to a pinhole mp4.

    balance=0.0 → no black borders (some FOV is cropped at the edges).
    balance=1.0 → full FOV (with black border crescents at corners).

    Returns (K_pinhole, fps, n_frames_written).
    """
    W, H = size
    cap = cv2.VideoCapture(str(src))
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {src}")
    fps = cap.get(cv2.CAP_PROP_FPS)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # New pinhole K. Keeping the output size identical to the input.
    K_new = cv2.fisheye.estimateNewCameraMatrixForUndistortRectify(
        K, D, (W, H), np.eye(3), balance=balance
    )
    map1, map2 = cv2.fisheye.initUndistortRectifyMap(
        K, D, np.eye(3), K_new, (W, H), cv2.CV_16SC2
    )

    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(dst), fourcc, fps, (W, H))
    if not writer.isOpened():
        raise RuntimeError(f"Could not open writer: {dst}")

    written = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        und = cv2.remap(frame, map1, map2, interpolation=cv2.INTER_LINEAR)
        writer.write(und)
        written += 1
        if written % 100 == 0:
            print(f"    undistort: {written}/{total}", flush=True)
    cap.release()
    writer.release()
    return K_new, float(fps), written


# ---------------------------------------------------------------------------
# Intrinsics yaml for MASt3R-SLAM
# ---------------------------------------------------------------------------


def write_pinhole_intrinsics(path: Path, K: np.ndarray, size: tuple[int, int]) -> None:
    W, H = size
    fx, fy = float(K[0, 0]), float(K[1, 1])
    cx, cy = float(K[0, 2]), float(K[1, 2])
    path.write_text(
        f"# Auto-generated by run_grabette_episode.py — pinhole intrinsics\n"
        f"# after fisheye undistortion of the original GRABETTE camera.\n"
        f"width: {W}\n"
        f"height: {H}\n"
        f"calibration: [{fx:.6f}, {fy:.6f}, {cx:.6f}, {cy:.6f}]\n"
    )


# ---------------------------------------------------------------------------
# MASt3R-SLAM invocation
# ---------------------------------------------------------------------------


def run_mast3r_slam(
    pinhole_video: Path,
    intrinsics_yaml: Path,
    save_as: str,
    config: str = "config/calib.yaml",
) -> Path:
    """Invoke main.py inside the current process's venv, return the TUM file path."""
    cmd = [
        "uv",
        "run",
        "python",
        str(REPO_ROOT / "main.py"),
        "--dataset",
        str(pinhole_video),
        "--config",
        config,
        "--calib",
        str(intrinsics_yaml),
        "--no-viz",
        "--save-as",
        save_as,
    ]
    print(f"==> {' '.join(cmd)}", flush=True)
    subprocess.run(cmd, cwd=REPO_ROOT, check=True)
    traj = REPO_ROOT / "logs" / save_as / f"{pinhole_video.stem}.txt"
    if not traj.is_file():
        raise FileNotFoundError(f"MASt3R-SLAM did not produce {traj}")
    return traj


# ---------------------------------------------------------------------------
# TUM → grabette CSV
# ---------------------------------------------------------------------------


def tum_to_grabette_csv(
    tum_path: Path,
    out_csv: Path,
    n_frames: int,
    fps: float,
    stride: int,
) -> None:
    """Convert MASt3R-SLAM's TUM keyframe trajectory to grabette per-frame CSV.

    grabette format (1 row per video frame_idx):
        frame_idx,timestamp,state,is_lost,is_keyframe,x,y,z,q_x,q_y,q_z,q_w

    MASt3R-SLAM TUM rows correspond to keyframes only. The TUM `t` column is
    `subsampled_idx / fps`, so the original video frame_idx is
    `round(t * fps) * stride`.
    """
    # Read TUM, build {frame_idx -> pose}
    tum_rows = []
    with open(tum_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) != 8:
                continue
            t = float(parts[0])
            x, y, z = (float(v) for v in parts[1:4])
            qx, qy, qz, qw = (float(v) for v in parts[4:8])
            sub_idx = int(round(t * fps))
            frame_idx = sub_idx * stride
            tum_rows.append((frame_idx, x, y, z, qx, qy, qz, qw))
    keyframe_map = {row[0]: row[1:] for row in tum_rows}
    print(f"  Keyframes parsed from TUM: {len(keyframe_map)}", flush=True)

    # Emit one row per video frame.
    with open(out_csv, "w") as f:
        f.write(
            "frame_idx,timestamp,state,is_lost,is_keyframe,x,y,z,q_x,q_y,q_z,q_w\n"
        )
        for frame_idx in range(n_frames):
            t = frame_idx / fps
            if frame_idx in keyframe_map:
                x, y, z, qx, qy, qz, qw = keyframe_map[frame_idx]
                f.write(
                    f"{frame_idx},{t:.6f},2,false,true,"
                    f"{x:.9f},{y:.9f},{z:.9f},"
                    f"{qx:.9f},{qy:.9f},{qz:.9f},{qw:.9f}\n"
                )
            else:
                f.write(
                    f"{frame_idx},{t:.6f},3,true,false,0,0,0,0,0,0,0\n"
                )


# ---------------------------------------------------------------------------
# Glue
# ---------------------------------------------------------------------------


def read_metadata(episode: Path) -> dict:
    meta = json.loads((episode / "metadata.json").read_text())
    return {
        "fps": float(meta["fps"]),
        "frame_count": int(meta["frame_count"]),
    }


def read_subsample_stride(config_path: Path) -> int:
    cfg = yaml.safe_load(config_path.read_text())
    if "inherit" in cfg:
        parent_cfg = yaml.safe_load((REPO_ROOT / cfg["inherit"]).read_text())
        # child overrides parent
        if "dataset" in parent_cfg:
            parent_cfg["dataset"].update(cfg.get("dataset", {}))
            cfg = parent_cfg | cfg
            cfg["dataset"] = parent_cfg["dataset"]
    return int(cfg.get("dataset", {}).get("subsample", 1))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--episode", required=True, type=Path,
                    help="Path to grabette episode dir (with raw_video.mp4 + metadata.json)")
    ap.add_argument("--calib", required=True, type=Path,
                    help="ORB-SLAM3-style YAML with KannalaBrandt8 intrinsics")
    ap.add_argument("--save-as", required=True,
                    help="Subdir name under logs/ for MASt3R-SLAM output")
    ap.add_argument("--config", default="config/calib.yaml",
                    help="MASt3R-SLAM config (default: config/calib.yaml)")
    ap.add_argument("--balance", type=float, default=0.0,
                    help="Fisheye undistortion balance: 0=cropped no-black, 1=full FOV")
    ap.add_argument("--reuse-pinhole", action="store_true",
                    help="Skip undistortion if raw_video_pinhole.mp4 already exists")
    args = ap.parse_args()

    episode = args.episode.resolve()
    if not episode.is_dir():
        sys.exit(f"Not a directory: {episode}")

    raw_video = episode / "raw_video.mp4"
    if not raw_video.is_file():
        sys.exit(f"Missing raw_video.mp4 in {episode}")

    pinhole_video = episode / "raw_video_pinhole.mp4"
    pinhole_yaml = episode / "intrinsics_pinhole.yaml"

    meta = read_metadata(episode)
    print(f"Episode: {episode}")
    print(f"  fps={meta['fps']}  frames={meta['frame_count']}")

    cfg = load_orbslam3_yaml(args.calib)
    K, D, size = extract_fisheye_intrinsics(cfg)
    print(f"  fisheye K=\n{K}\n  D={D}  size={size}")

    if args.reuse_pinhole and pinhole_video.is_file() and pinhole_yaml.is_file():
        print(f"==> Reusing existing {pinhole_video.name}")
        K_pin = None  # not needed downstream; intrinsics yaml already on disk
    else:
        print(f"==> Undistorting fisheye → pinhole: {pinhole_video.name}")
        K_pin, fps_check, n_written = undistort_video(
            raw_video, pinhole_video, K, D, size, balance=args.balance
        )
        if abs(fps_check - meta["fps"]) > 1.0:
            print(f"    warning: video fps {fps_check} != metadata fps {meta['fps']}")
        if n_written != meta["frame_count"]:
            print(f"    warning: wrote {n_written} frames, metadata says {meta['frame_count']}")
        print(f"==> Pinhole intrinsics: {pinhole_yaml.name}")
        write_pinhole_intrinsics(pinhole_yaml, K_pin, size)
        print(f"    K_pinhole=\n{K_pin}")

    print(f"==> Running MASt3R-SLAM (--save-as {args.save_as})")
    tum_path = run_mast3r_slam(
        pinhole_video=pinhole_video,
        intrinsics_yaml=pinhole_yaml,
        save_as=args.save_as,
        config=args.config,
    )
    print(f"  TUM trajectory: {tum_path}")

    stride = read_subsample_stride(REPO_ROOT / args.config)
    print(f"  subsample stride from {args.config}: {stride}")

    out_csv = episode / "mast3r_camera_trajectory.csv"
    print(f"==> Writing grabette-format CSV: {out_csv.name}")
    tum_to_grabette_csv(
        tum_path=tum_path,
        out_csv=out_csv,
        n_frames=meta["frame_count"],
        fps=meta["fps"],
        stride=stride,
    )

    # Also copy the TUM trajectory next to it for completeness.
    shutil.copy2(tum_path, episode / f"mast3r_{tum_path.name}")
    print(f"\nDone.")
    print(f"  CSV:  {out_csv}")
    print(f"  Visualize:  uv run python scripts/visualize_trajectory.py {episode}  "
          f"# (in grabette-data)")
    print(f"  Compare to ORB:  add  -r {episode}/mapping_camera_trajectory.csv")


if __name__ == "__main__":
    main()
